### ISSUE TITLE
在调用 nextIdSimple 获取id时，batchSize = 0 时会出现越界

### ISSUE THREAD

**Issue by iheshichao** [didi/tinyid#22]
curl http://127.0.0.1:9999/tinyid/id/nextIdSimple -d 'token=0f673adf80504e2eaa552f5d791b644c&bizType=test&batchSize=0'

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:824) ~[?:1.8.0_241]
	at java.lang.StringBuilder.deleteCharAt(StringBuilder.java:253) ~[?:1.8.0_241]
	at com.xiaoju.uemc.tinyid.server.controller.IdContronller.nextIdSimple(IdContronller.java:85) [classes/:?]

**Comment by 351524388** [comment]
确实有这个问题，可以考虑在checkBatchSize方法中改进一下
